// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"PMSApp/app/basic"
	"PMSApp/app/config"
	"PMSApp/app/controllers"
	"PMSApp/app/daos"
	"PMSApp/app/models"
	"PMSApp/app/routers"
	"PMSApp/app/utils"
	"net/http"
)

// Injectors from wire.go:

func BuildInjector() *http.Server {
	configType := config.NewConfig()
	writeSyncer := basic.GetLogWriter(configType)
	encoder := basic.GetEncoder()
	logger := basic.NewLogger(configType, writeSyncer, encoder)
	ginx := utils.Ginx{
		Logger: logger,
	}
	db := basic.NewDB(configType)
	userInfo := &daos.UserInfo{
		DB:     db,
		Logger: logger,
	}
	userDetail := &daos.UserDetail{
		DB:     db,
		Logger: logger,
	}
	user := models.NewUser(userInfo, userDetail, logger)
	login := &controllers.Login{
		Logger:    logger,
		Util:      ginx,
		UserModel: user,
	}
	router := &routers.Router{
		LoginAPI: login,
	}
	server := NewApp(configType, router)
	return server
}
