app:
  port: :8000
  mode: dev
  timeout: 5
  secret: secret
db:
  url: root:password@tcp(url.net:3306)/management?charset=utf8&parseTime=True&loc=Local
log:
  filename: ./logs/gin.log
  maxSize: 128
  maxBackups: 3
  maxAge: 7
  compress: true
